version: '3.8'

services:
    database: 
        container_name: lirica-database
        image: postgres
        ports: 
            - 5431:5432
        environment: 
            - POSTGRES_USER=lirica_admin
            - POSTGRES_PASSWORD=master123
            - POSTGRES_DB=liricahealth
        volumes: 
            - ./docker-volumes/postgresql:/var/lib/postgresql
        networks: 
            - nest-network
    server:
        container_name: lirica-backend
        build:
            context: .
            dockerfile: ./Dockerfile
        networks: 
            - nest-network
        depends_on: 
            - database
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
networks: 
    nest-network:
        external: true
